# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urmhs_wrk_session_details.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wrk_session_details_dialog(object):
    def setupUi(self, wrk_session_details_dialog):
        wrk_session_details_dialog.setObjectName("wrk_session_details_dialog")
        wrk_session_details_dialog.resize(830, 500)
        wrk_session_details_dialog.setMinimumSize(QtCore.QSize(830, 500))
        wrk_session_details_dialog.setMaximumSize(QtCore.QSize(830, 500))
        self.buttonBox = QtWidgets.QDialogButtonBox(wrk_session_details_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(650, 460, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.wrk_session_descr = QtWidgets.QTextEdit(wrk_session_details_dialog)
        self.wrk_session_descr.setGeometry(QtCore.QRect(80, 70, 431, 41))
        self.wrk_session_descr.setObjectName("wrk_session_descr")
        self.wrk_session_name = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.wrk_session_name.setGeometry(QtCore.QRect(230, 10, 281, 20))
        self.wrk_session_name.setObjectName("wrk_session_name")
        self.label_2 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 41, 21))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label_5.setObjectName("label_5")
        self.wrk_session_id = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.wrk_session_id.setGeometry(QtCore.QRect(80, 10, 61, 20))
        self.wrk_session_id.setObjectName("wrk_session_id")
        self.created_by = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.created_by.setGeometry(QtCore.QRect(80, 120, 161, 20))
        self.created_by.setObjectName("created_by")
        self.label_7 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_7.setGeometry(QtCore.QRect(270, 120, 71, 21))
        self.label_7.setObjectName("label_7")
        self.creation_date = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.creation_date.setGeometry(QtCore.QRect(350, 120, 161, 20))
        self.creation_date.setObjectName("creation_date")
        self.label_8 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 47, 21))
        self.label_8.setObjectName("label_8")
        self.wrk_session_status = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.wrk_session_status.setGeometry(QtCore.QRect(80, 40, 211, 20))
        self.wrk_session_status.setObjectName("wrk_session_status")
        self.label_6 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 71, 21))
        self.label_6.setObjectName("label_6")
        self.save_date = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.save_date.setGeometry(QtCore.QRect(350, 150, 161, 20))
        self.save_date.setObjectName("save_date")
        self.saved_by = QtWidgets.QLineEdit(wrk_session_details_dialog)
        self.saved_by.setGeometry(QtCore.QRect(80, 150, 161, 20))
        self.saved_by.setObjectName("saved_by")
        self.label_9 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_9.setGeometry(QtCore.QRect(270, 150, 71, 21))
        self.label_9.setObjectName("label_9")
        self.wrk_session_history_list = QtWidgets.QTableWidget(wrk_session_details_dialog)
        self.wrk_session_history_list.setGeometry(QtCore.QRect(10, 210, 811, 241))
        self.wrk_session_history_list.setObjectName("wrk_session_history_list")
        self.wrk_session_history_list.setColumnCount(0)
        self.wrk_session_history_list.setRowCount(0)
        self.label_10 = QtWidgets.QLabel(wrk_session_details_dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.label_10.setObjectName("label_10")
        self.lbl_image = QtWidgets.QLabel(wrk_session_details_dialog)
        self.lbl_image.setGeometry(QtCore.QRect(520, 10, 301, 191))
        self.lbl_image.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_image.setText("")
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setObjectName("lbl_image")

        self.retranslateUi(wrk_session_details_dialog)
        self.buttonBox.accepted.connect(wrk_session_details_dialog.accept)
        self.buttonBox.rejected.connect(wrk_session_details_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(wrk_session_details_dialog)

    def retranslateUi(self, wrk_session_details_dialog):
        _translate = QtCore.QCoreApplication.translate
        wrk_session_details_dialog.setWindowTitle(_translate("wrk_session_details_dialog", "URMHS - Work session detail"))
        self.label_2.setText(_translate("wrk_session_details_dialog", "Description:"))
        self.label_3.setText(_translate("wrk_session_details_dialog", "Created by:"))
        self.label.setText(_translate("wrk_session_details_dialog", "Name:"))
        self.label_5.setText(_translate("wrk_session_details_dialog", "Id:"))
        self.label_7.setText(_translate("wrk_session_details_dialog", "Creation date:"))
        self.label_8.setText(_translate("wrk_session_details_dialog", "Status:"))
        self.label_6.setText(_translate("wrk_session_details_dialog", "Saved by:"))
        self.label_9.setText(_translate("wrk_session_details_dialog", "Save date:"))
        self.label_10.setText(_translate("wrk_session_details_dialog", "History:"))

